# paperback: paper backup generator suitable for long-term storage
# Copyright (C) 2018-2020 Aleksa Sarai <cyphar@cyphar.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[package]
name = "paperback-core"
version = "0.0.0"
authors = ["Aleksa Sarai <cyphar@cyphar.com>"]

description = "Paper backup generator suitable for long-term storage."
repository = "https://github.com/cyphar/paperback"
readme = "README.md"

keywords = ["shamir", "secret", "crypto", "paper", "backup"]
categories = ["cryptography"]
edition = "2018"

[dependencies]
aead = "^0.2"
multihash = "^0.10"
chacha20poly1305 = "^0.3"
digest = "^0.8"
"ed25519-dalek" = "^1.0.0-pre.3"
nom = "^5"
rand = "^0.7"
serde = { version = "^1", features = ["derive"] }
"tiny-bip39" = "^0.7"
typenum = "^1"
"unsigned-varint" = "^0.3"
zbase32 = "^0.1"

"paperback-shamir" = { path = "../paperback-shamir" }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
